import { StyleSheet } from "react-native";

export const listCardStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
      backgroundColor: colors.bg400,
      width: "100%",
      height: 90,
      paddingHorizontal: 15,
      borderRadius: 10,
      boxShadow: colors.shadow100,
    },
    wrapper: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    titleWrapper: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 15,
      width: "85%",
    },
    userContainer: {
      position: "relative",
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      width: "15%",
      height: 20,
    },
    user: {
      position: "absolute",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: 20,
      height: 20,
      borderRadius: 100,
      borderWidth: 1,
      borderColor: colors.n800,
      backgroundColor: colors.n300,
    },
    name: {
      color: colors.text,
      fontSize: 8,
    },
    title: {
      color: colors.text,
      fontSize: 18,
      marginTop: -4,
    },
    svg: {
      width: 24,
      height: 24,
    },
    bar: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      backgroundColor: colors.n100,
      borderRadius: 100,
      width: "85%",
      height: "100%",
    },
    progress: {
      backgroundColor: colors.p300,
      borderRadius: 100,
      height: "100%",
      zIndex: 100,
    },
    indicator: {
      color: colors.text,
      fontSize: 14,
    },
  });
