import { StyleSheet, Dimensions } from "react-native";

const screenHeight = Dimensions.get("window").height;

export const newListStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      position: "absolute",
      top: 0,
      left: 0,
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      backgroundColor: colors.bg200,
      paddingTop: "13%",
      paddingHorizontal: "5%",
      width: "100%",
      height: "100%",
      zIndex: 2,
    },
    arrowContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "flex-start",
    },
    arrow: {
      width: 30,
      height: 30,
    },
    imageContainer: {
      position: "relative",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: "30%",
      aspectRatio: 1 / 1,
      marginTop: 10,
    },
    blob: {
      position: "absolute",
      top: 0,
      left: 0,
      height: "100%",
      aspectRatio: 1 / 1,
      transform: [{ rotate: "-45deg" }],
      zIndex: -1,
    },
    image: {
      height: "70%",
      aspectRatio: 1 / 1,
    },
    inputContainer: {
      position: "relative",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      width: "100%",
      height: 55,
    },
    svg: {
      position: "absolute",
      top: 18,
      left: 15,
      width: 30,
      height: 30,
      zIndex: 1,
    },
    input: {
      backgroundColor: colors.n50,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.n300,
      borderRadius: 15,
      fontSize: 16,
      width: "100%",
      height: "100%",
      paddingLeft: 50,
      paddingRight: 25,
    },
    inputError: { borderColor: colors.danger, color: colors.danger },
    error: {
      color: colors.danger,
      width: "100%",
      fontSize: 10,
      marginTop: 10,
    },
    subtitle: {
      alignSelf: "flex-start",
      color: colors.n700,
      fontSize: 14,
      marginTop: 30,
    },
    chipContainer: {
      position: "relative",
      width: "100%",
      height: 30,
      marginTop: 10,
    },
    gradient: {
      position: "absolute",
      top: 0,
      bottom: 0,
      width: 30,
      zIndex: 1,
    },
    left: {
      left: 0,
    },
    right: {
      right: 0,
    },
    listContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.n100,
      borderRadius: 100,
      height: 30,
      paddingHorizontal: 16,
      marginRight: 10,
    },
    chipText: {
      color: colors.n500,
      fontSize: 12,
      textAlign: "center",
    },
    text: {
      color: colors.text_l,
      fontSize: 24,
      textAlign: "center",
      width: "80%",
    },
    scrollContainer: {
      position: "relative",
      flexGrow: 0,
      width: "100%",
      height: screenHeight * 0.2,
    },
    contentContainer: {
      flexDirection: "row",
      justifyContent: "flex-start",
      flexWrap: "wrap",
      height: "100%",
      gap: 15,
      paddingVertical: 15,
    },
    gradientTop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 30,
      zIndex: 1,
    },
    gradientBottom: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      height: 30,
      zIndex: 1,
    },
    friends: {
      flexDirection: "column",
      alignItems: "flex-start",
      alignSelf: "flex-start",
      justifyContent: "flex-start",
      borderColor: colors.n300,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    selected: {
      backgroundColor: colors.p50,
      borderColor: colors.p100,
    },
    username: {
      color: colors.n700,
      fontSize: 16,
    },
    email: {
      color: colors.n400,
      fontSize: 10,
    },
    button: {
      position: "absolute",
      bottom: 40,
      backgroundColor: colors.p400,
      width: "100%",
      paddingVertical: 15,
      borderRadius: 100,
      boxShadow: colors.shadow,
    },
    btnText: {
      color: colors.text_l,
      textAlign: "center",
      fontSize: 16,
    },
  });
