import { StyleSheet } from "react-native";

export const actionSheetStyles = (colors: any) =>
  StyleSheet.create({
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      justifyContent: "flex-end",
      backgroundColor: "rgba(0,0,0,0.4)",
      height: "100%",
      width: "100%",
    },
    title: {
      color: colors.n700,
      borderBottomColor: colors.n100,
      borderBottomWidth: 1,
      fontSize: 22,
      textAlign: "center",
      paddingBottom: 20,
    },
    sheet: {
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 40,
      width: "100%",
    },
    option: {
      paddingVertical: 16,
      alignItems: "center",
    },
    optionText: {
      color: colors.n400,
      fontSize: 16,
    },
    back: {
      color: colors.p300,
      fontSize: 16,
      textAlign: "right",
      paddingBottom: 40,
    },
    text: {
      color: colors.text,
      fontSize: 20,
      textAlign: "center",
      paddingBottom: 40,
    },
    btnContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    btn: {
      width: "45%",
      paddingVertical: 16,
      borderRadius: 10,
    },
    btnLabel: {
      color: colors.n600,
      fontSize: 16,
      textAlign: "center",
    },
    inputContainer: {
      position: "relative",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      width: "100%",
      height: 55,
    },
    svg: {
      position: "absolute",
      top: 18,
      left: 15,
      width: 30,
      height: 30,
      zIndex: 1,
    },
    input: {
      backgroundColor: colors.n50,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.n300,
      borderRadius: 15,
      fontSize: 16,
      width: "100%",
      height: "100%",
      paddingLeft: 50,
      paddingRight: 25,
    },
    inputError: { borderColor: colors.danger, color: colors.danger },
    error: {
      color: colors.danger,
      width: "100%",
      fontSize: 10,
      marginTop: 10,
    },
    button: {
      backgroundColor: colors.p400,
      width: "100%",
      paddingVertical: 15,
      borderRadius: 100,
      boxShadow: colors.shadow,
      marginTop: 50,
    },
    btnText: {
      color: colors.text_l,
      textAlign: "center",
      fontSize: 16,
    },
  });
