import { StyleSheet } from "react-native";

export const homeStyles = (colors: any) =>
  StyleSheet.create({
    page: {
      flex: 1,
      backgroundColor: colors.bg200,
    },
    container: {
      position: "relative",
      top: 0,
      left: 0,
      paddingHorizontal: "5%",
    },
    scrollContainer: {
      justifyContent: "flex-start",
      paddingBottom: "80%",
    },
    emptyContainer: {
      width: "100%",
      height: "60%",
      paddingHorizontal: "5%",
    },
    empty: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-end",
      width: "100%",
      height: "50%",
      paddingHorizontal: "5%",
    },
    blob: {
      position: "absolute",
      top: "23%",
      left: "20%",
      height: "100%",
      aspectRatio: 1 / 1,
      transform: [{ rotate: "-45deg" }],
      zIndex: 0,
    },
    image: {
      objectFit: "contain",
      height: "70%",
      aspectRatio: 1 / 1,
    },
    emptyText: {
      fontSize: 22,
      color: colors.text,
      textAlign: "center",
      marginTop: 70,
    },
    emptySubText: {
      fontSize: 15,
      color: colors.n400,
      textAlign: "center",
      marginTop: 20,
    },
    header: {
      position: "relative",
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: colors.bg200,
      width: "100%",
      paddingTop: 50,
      paddingBottom: 20,
      paddingHorizontal: "5%",
    },
    pageTitle: {
      fontSize: 20,
      color: colors.text,
      marginTop: -5,
    },
    svg: {
      objectFit: "contain",
      aspectRatio: 1 / 1,
      height: 27,
    },
    hasNotification: {
      position: "absolute",
      top: -2,
      right: 3,
      backgroundColor: colors.danger,
      borderRadius: 100,
      width: 10,
      height: 10,
    },
    title: {
      fontSize: 14,
      color: colors.n200,
      marginTop: 20,
    },
    button: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      gap: 5,
      backgroundColor: colors.p400,
      boxShadow: colors.shadow,
      borderRadius: 100,
      width: "90%",
      alignSelf: "center",
      paddingVertical: 15,
      // marginTop: 100,
    },
    buttonSmall: {
      position: "absolute",
      width: "40%",
      alignSelf: "flex-end",
      marginTop: 0,
      marginRight: "5%",
      bottom: "15%",
      zIndex: 2,
    },
    btnText: {
      color: "hsl(0, 0%, 96%)",
      fontSize: 14,
    },
  });
